name: checks
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - name: Install Node.js dependencies
        run: npm install --include=dev --prod

      - name: install dev
        run: npm install --only=dev
      
      - name: view list
        run: npm list --depth=0

      - name: remove whatever was modifed
        run: git reset --hard && git clean -fd

      - name: run lint
        uses: wearerequired/lint-action@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          auto_fix: true
      
      - name: unit test
        run: npm run test